# -*- coding: utf-8 -*-
"""Test_SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vAhTsPihIu8bgNOXC0sartsY5GGp344k
"""

import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing import image
import joblib  # Thư viện nạp mô hình SVM
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

# Tắt cảnh báo TensorFlow
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'

# =====================================================================
# CHUẨN BỊ MÔI TRƯỜNG & ĐƯỜNG DẪN
# =====================================================================
IMG_SIZE = (224, 224)
BATCH_SIZE = 32
class_names = ['cardboard', 'glass', 'metal', 'paper', 'plastic', 'trash']
svm_model_path = r'D:\study\CT312\garbage-classification-web\backend\ml\svm_garbage_model (1).joblib' 

# =====================================================================
# KHỞI TẠO BỘ TRÍCH XUẤT ĐẶC TRƯNG MOBILENETV2 VÀ SVM ĐỂ DÙNG CHO API
# =====================================================================
print("\n--- Đang nạp mô hình MobileNetV2 và SVM ---")
preprocess_input = tf.keras.applications.mobilenet_v2.preprocess_input
base_model = tf.keras.applications.MobileNetV2(
    weights='imagenet', include_top=False, input_shape=(224, 224, 3), pooling='avg'
)

if os.path.exists(svm_model_path):
    svm_model = joblib.load(svm_model_path)
else:
    print(f"❌ LỖI: Không tìm thấy file model SVM tại '{svm_model_path}'.")
    svm_model = None

# =====================================================================
# HÀM THỬ NGHIỆM DỰ ĐOÁN MỘT ẢNH THỰC TẾ BẤT KỲ
# =====================================================================
def predict_single_image_fixed(img_path, model_svm, base_extractor, show_plot=False):
    print(f"\n--- Đang nhận diện ảnh thực tế: {img_path} ---")

    img = image.load_img(img_path, target_size=(224, 224))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)

    preprocessed_img = preprocess_input(img_array)
    features = base_extractor.predict(preprocessed_img, verbose=0)
    pred_class_idx = model_svm.predict(features)[0]
    predicted_label = class_names[pred_class_idx]

    if show_plot:
        plt.figure(figsize=(5, 5))
        plt.imshow(img)
        plt.title(f"Kết quả nhận diện: {predicted_label.upper()}", color='green', fontsize=12, fontweight='bold')
        plt.axis('off')
        plt.show()

    print(f"👉 Hệ thống phân loại: {predicted_label}")
    return predicted_label

# =====================================================================
# TÍCH HỢP FASTAPI (CHẠY QUA UVICORN)
# =====================================================================
app = FastAPI()

class PredictRequest(BaseModel):
    image_path: str

@app.post("/predict")
def predict_image(request: PredictRequest):
    if not svm_model:
        raise HTTPException(status_code=500, detail="Mô hình SVM chưa được nạp.")
    
    img_path = request.image_path
    if not os.path.exists(img_path):
        raise HTTPException(status_code=400, detail=f"Không tìm thấy ảnh: {img_path}")
        
    try:
        predicted_label = predict_single_image_fixed(img_path, svm_model, base_model, show_plot=False)
        return {
            "success": True,
            "predictedClass": predicted_label,
            "confidence": "N/A"
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/")
def read_root():
    return {"message": "Garbage Classification FastAPI is running directly from test_svm.py"}


# =====================================================================
# CHẠY ĐÁNH GIÁ MÔ HÌNH NẾU CHẠY TRỰC TIẾP FILE NÀY (PYTHON TEST_SVM.PY)
# =====================================================================
if __name__ == '__main__':
    # 1. TẢI VÀ ĐỊNH NGHĨA TẬP DỮ LIỆU KIỂM THỬ (VAL_DS)
    print("--- Đang tải dữ liệu kiểm thử---")
    path = r'D:\study\CT312\garbage-classification-web\backend\ml\dataset'

    val_ds = tf.keras.utils.image_dataset_from_directory(
        path,
        validation_split=0.2,
        subset="validation",
        seed=42, 
        image_size=IMG_SIZE,
        batch_size=BATCH_SIZE
    )

    AUTOTUNE = tf.data.AUTOTUNE
    val_ds = val_ds.prefetch(buffer_size=AUTOTUNE)

    # 3. TRÍCH XUẤT ĐẶC TRƯNG TỪ TẬP KIỂM THỬ
    print("\n--- Đang trích xuất đặc trưng tập kiểm thử ---")
    X_val_features = []
    y_val_labels = []

    for images, labels in val_ds:
        preprocessed_images = preprocess_input(images)
        features = base_model.predict(preprocessed_images, verbose=0)

        X_val_features.append(features)
        y_val_labels.append(labels.numpy())

    X_val_features = np.concatenate(X_val_features, axis=0)
    y_val_labels = np.concatenate(y_val_labels, axis=0)

    # 4. ĐÁNH GIÁ ĐỂ LẤY SỐ LIỆU VIẾT BÀI BÁO
    if svm_model:
        y_pred = svm_model.predict(X_val_features)
        acc = accuracy_score(y_val_labels, y_pred)
        print("\n==================================================")
        print(f"🔥 ĐỘ CHÍNH XÁC TỔNG THỂ (Test Accuracy): {acc * 100:.2f}%")
        print("==================================================")

        print("\n📊 BÁO CÁO CHI TIẾT (Classification Report):")
        print(classification_report(y_val_labels, y_pred, target_names=class_names))

        print("\n🎨 Đang vẽ Ma trận nhầm lẫn (Confusion Matrix)...")
        cm = confusion_matrix(y_val_labels, y_pred)
        disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)

        fig, ax = plt.subplots(figsize=(8, 8))
        disp.plot(cmap=plt.cm.Blues, ax=ax, values_format='d')
        plt.title("Ma trận nhầm lẫn của mô hình MobileNetV2 + SVM", fontsize=12, fontweight='bold')
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()

        image_test_name = r"D:\study\CT312\garbage-classification-web\backend\ml\Image_Test\1.jpg"
        if os.path.exists(image_test_name):
            predict_single_image_fixed(image_test_name, svm_model, base_model, show_plot=True)
        else:
            print(f"⚠️ Không tìm thấy file ảnh tại đường dẫn: {image_test_name}")

        print("Các mã nhãn thực tế có trong tập Test:", np.unique(y_val_labels))
        print("Các mã nhãn mô hình SVM dự đoán ra:", np.unique(y_pred))
        print("Tổng số ảnh mang đi test:", len(y_val_labels))