# -*- coding: utf-8 -*-
"""Train_svm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zQ2AA1J5ZApUwYj8c2EQmP2tRVd2lcK1
"""

import os
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.applications import MobileNetV2
import kagglehub
import joblib
from sklearn.svm import LinearSVC
from sklearn.model_selection import GridSearchCV # Thư viện tìm tham số tối ưu

# 1. CẤU HÌNH & TẢI DATA
IMG_SIZE = (224, 224)
BATCH_SIZE = 32
seed_value = 42

path = kagglehub.dataset_download("asdasdasasdas/garbage-classification")
path = os.path.join(path, "Garbage classification/Garbage classification")
train_ds = tf.keras.utils.image_dataset_from_directory(
    path, validation_split=0.2, subset="training", seed=seed_value,
    image_size=IMG_SIZE, batch_size=BATCH_SIZE
)

# 2. ĐỊNH NGHĨA LỚP TĂNG CƯỜNG ẢNH (CHỐNG HỌC VẸT)
data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal_and_vertical"),
    layers.RandomRotation(0.15),
    layers.RandomZoom(0.1),
])

preprocess_input = tf.keras.applications.mobilenet_v2.preprocess_input
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224, 3), pooling='avg')

# 3. TRÍCH XUẤT ĐẶC TRƯNG TỪ ẢNH ĐÃ ĐƯỢC TĂNG CƯỜNG
print("\n--- Đang trích đặc trưng kết hợp Tăng cường ảnh ---")
X_train_features = []
y_train_labels = []

for images, labels in train_ds:
    # Bổ sung bước Augmentation trước khi trích đặc trưng để đa dạng hóa dữ liệu
    augmented_images = data_augmentation(images)
    preprocessed_images = preprocess_input(augmented_images)
    features = base_model.predict(preprocessed_images, verbose=0)

    X_train_features.append(features)
    y_train_labels.append(labels.numpy())

X_train_features = np.concatenate(X_train_features, axis=0)
y_train_labels = np.concatenate(y_train_labels, axis=0)

# 4. DÙNG GRIDSEARCHCV ĐỂ TÌM THAM SỐ C CHỐNG OVERFITTING TỐT NHẤT
print("\n--- Đang quét tìm tham số C tối ưu để chống Overfitting ---")

# Thử nghiệm các giá trị C từ nhỏ (chống học vẹt mạnh) đến lớn
param_grid = {'C': [0.001, 0.01, 0.1, 1.0]}

# Khởi tạo LinearSVC
base_svm = LinearSVC(random_state=seed_value, max_iter=3000, dual=False)

# Thực hiện quét ngẫu nhiên ngắt đoạn (3-Fold Cross Validation)
grid_search = GridSearchCV(base_svm, param_grid, cv=3, scoring='accuracy', verbose=2)
grid_search.fit(X_train_features, y_train_labels)

# Xuất ra kết quả tối ưu
print(f"\n=> Tham số C tốt nhất giúp chống Overfitting là: {grid_search.best_params_['C']}")
print(f"=> Độ chính xác ước tính (CV Score): {grid_search.best_score_ * 100:.2f}%")

# Lấy ra mô hình tốt nhất đã được cấu hình tham số chống học vẹt
best_svm_model = grid_search.best_estimator_

# 5. LƯU MÔ HÌNH TỐI ƯU
model_name = 'svm_garbage_model.joblib'
joblib.dump(best_svm_model, model_name)
print(f"\n🎉 Đã lưu mô hình SVM tối ưu tại file: {model_name}")